Fixes #1727 - Add PUT/PATCH/DELETE for zaakeigenschappen
VNG-Realisatie/zaken-api pull request #195
Opened 2021-03-18 15:09 UTC by SilviaAmAm

Fixes https://github.com/VNG-Realisatie/gemma-zaken/issues/1727

2021-03-24 14:49 UTC, sergei-maertens requested changes
There's a lot of stuff related to 1.1 features that snuck in the API schema, did you base this branch of master rather than `stable/1.0.x` by any change?

2021-03-24 15:29 UTC, SilviaAmAm commented
As far as I can see, I based on stable/1.0.x :thinking: 
If I `git log`, then the last commit before the ones I added is:
```
commit 35210a923b9e9265fe5647b3c2334fccfeca1096 (upstream/stable/1.0.x)
Merge: b2c0975 f02b644
Author: Steven Bal 
Date:   Mon Jan 11 10:12:51 2021 +0100

    Merge pull request #193 from VNG-Realisatie/issue/fix-ci
    
    :green_heart: Add DEPLOY_BOT_TOKEN to docker push workflow
```

2021-05-03 09:26 UTC, sergei-maertens approved these changes

2021-07-22 07:22 UTC, sergei-maertens commented
Closing to re-open against the master branch so that this could go in a 1.2 release.

2021-07-23 09:10 UTC, sergei-maertens requested changes
I'm missing the right notifications mixin so that notifications are also emitted on (partial) update and destroy of zaakeigenschappen.

2021-07-28 08:38 UTC, sergei-maertens commented on src/zrc/api/serializers/core.py
> +
wouldn't we have achieved the same by specifying `"validators": [IsImmutableValidator()]` in the `extra_kwargs` for `zaak`?

2021-07-28 08:53 UTC, sergei-maertens approved these changes

2021-08-11 09:38 UTC, merged