Issue/#2194 aanmaken status
VNG-Realisatie/zaken-api pull request #261
Opened 2023-03-20 11:51 UTC by MatthijsBekendam

2023-03-20 14:27 UTC, MatthijsBekendam commented
from : https://github.com/orgs/VNG-Realisatie/projects/10?pane=issue&itemId=23374741

2023-03-21 09:12 UTC, joerivrij requested changes

2023-03-21 09:12 UTC, joerivrij commented on src/zrc/api/serializers/schema/core.py
> +    for AOS generation."""
AOS = OAS ?

2023-03-21 09:44 UTC, joerivrij approved these changes

2023-03-21 14:18 UTC, closed without merging